#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3333/projectx
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: passwd
#
#
#logging:
#  level:
#    root: debug
